config/routes.rb
Rails.application.routes.draw do
  root to: 'landing_page#home'

  get 'legal/termos_de_uso', to: 'landing_page#terms_of_service'
  get 'legal/privacidade', to: 'landing_page#privacy'
  get 'proposito', to: 'landing_page#purpose'
  get 'nossos-diferenciais', to: 'landing_page#differential'
  get 'pontos-educacao', to: 'landing_page#education_points'
  get 'nuestros-diferenciales', to: 'landing_page#differential'
  get 'puntos-educacion', to: 'landing_page#education_points'
  get 'futuros-lancamentos', to: 'landing_page#future_releases'
  get 'futuros-lanzamientos', to: 'landing_page#future_releases'
  get 'simulacao', to: 'landing_page#simulation'
  get 'simulacion', to: 'landing_page#simulation'
  post 'simulacao', to: 'landing_page#simulator'  
  get 'tour-360', to: 'landing_page#tour'  
  get 'sustentabilidade', to: 'landing_page#sustainability'

  get 'callback/document_signature', to: 'shop/contracts#callback'

  post 'webhooks/documents', to: 'webhook/documents#callback'

  localized do
    devise_for :users, only: :sessions, controllers: { sessions: :sessions }
    devise_for :users, only: :sessions, path: :admin

    unauthenticated :user do
      resources :document_downloads do         
        collection do 
          get :donwload_video
        end  
      end  
    end  

    authenticate :user do
      resources :document_downloads, only: [:show] do 
        member do 
          get :donwload_contract          
        end 

        collection do 
          get :donwload_video
        end  
      end  

      scope module: 'customer' do
        resource :contract, only: :show
        resource :user, only: [:edit, :update]
        resource :rg_document, only: [:edit, :update]
        resource :residence_document, only: [:edit, :update]
        resource :employment_document, only: [:edit, :update]
      end

      scope module: :shop do
        resource :bloc, only: [:edit, :update] do 
          get :back
        end 
        resource :pavement, only: [:edit, :update]
        resource :apartment, only: [:edit, :update]
        resources :apartments, only: [:queue] do 
          get :queue
        end    
        resource :document, only: [:edit, :update]
        resource :analyze, only: [:show]
        resource :contract, only: [:edit, :update]
        resource :analyze_contract, only: [:show]
        resource :analyze_bank, only: [:show]
      end

      scope :admin, as: 'admin', module: 'admin' do
        resources :contracts, only: :create
        resources :users, only: [:index, :show, :edit, :update, :destroy] do
          post :approved, on: :member
          post :approved_contract, on: :member   
          post :approved_contract_document, on: :member   
          post :signature_bank, on: :member   
          delete :refuse, on: :member  
          delete :refuse_contract, on: :member   
          delete :refuse_contract_document, on: :member   
          delete :refuse_bank, on: :member       
          
          post :reset_account, on: :member  

          resource :document, only: [:edit, :update]          
        end
      end
    end
  end
end

app/views/layouts/shared/_facebook_pixel.html.erb
<!-- Facebook Pixel Code -->

<script>

!function(f,b,e,v,n,t,s)

{if(f.fbq)return;n=f.fbq=function(){n.callMethod?

n.callMethod.apply(n,arguments):n.queue.push(arguments)};

if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';

n.queue=[];t=b.createElement(e);t.async=!0;

t.src=v;s=b.getElementsByTagName(e)[0];

s.parentNode.insertBefore(t,s)}(window,document,'script',

'https://connect.facebook.net/en_US/fbevents.js');


fbq('init', '2199793430296012'); 

fbq('track', 'PageView');

</script>

<noscript>

<img height="1" width="1" 

src="https://www.facebook.com/tr?id=2199793430296012&ev=PageView

&noscript=1"/>

</noscript>

<!-- End Facebook Pixel Code -->

app/views/layouts/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row menu-rights" style="padding: 55px 0;">
      <div class="col-md-12">        
        <%= t('landing_page.home.copyright') %>
        <ul class="social-media pull-right" style="margin-right: 50px;">
          <li>
            <%= link_to donwload_video_document_downloads_path, class: 'video-download', target: '_blank' do %>
              <i class="fa fa-download"></i>
            <% end %>                        
          </li>                                                                             
          <li>
            <a class="whatsapp" href="<%= t('landing_page.home.whatsapp') %>" target="_blank" app-href="<%= t('landing_page.home.app_url_facebook') %>">
              <i class="fa fa-whatsapp"></i>
            </a>
          </li>                                
          <li>
            <a href="<%= t('landing_page.home.facebook') %>" target="_blank" app-href="<%= t('landing_page.home.app_url_whatsapp') %>">
              <i class="fa fa-facebook"></i>
            </a>
          </li>                                      
        </ul>  
      </div>            
    </div>
  </div>
</footer>

app/views/layouts/shared/_footer_users.html.erb
<footer>
  <div class="container">
    <div class="row menu-rights">
      <div class="col-md-12">      
        <p>Copyright © 2017. Todos os direitos reservados</p>
      </div>
    </div>
    </div>
  </div>
</footer>

app/views/layouts/shared/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= Rails.application.secrets.google_analytics_key %>', 'auto');
  ga('send', 'pageview');

  document.addEventListener('DOMContentLoaded', function(event) {
    if (typeof ga === 'function' && typeof event !== 'undefined' && typeof event.data !== 'undefined') {
      ga('set', 'location', event.data.url);
      ga('send', 'pageview');
    }
  });
</script>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="pl15 pr15 container">
    <div class="navbar-header">
      <%= link_to t('title'), root_path, class: 'navbar-brand' %>
    </div>

    <p class="mr0 navbar-text right">
      <%= link_to t('navbar.sign_out'), destroy_user_session_path, method: :delete, class: 'navbar-link' %>
    </p>
  </div>
</nav>

app/views/layouts/shared/_sentry.html.erb
<%= javascript_include_tag 'https://cdn.ravenjs.com/3.14.2/raven.min.js' %>
<script>Raven.config('https://5d200200e2c04ae1b0fa74c9c61264d7@sentry.io/164000').install();</script>

app/views/layouts/shared/_wizard.html.erb
<div class="container-wizard hidden-xs hidden-sm col-xs-height text-center">
  <nav class="wizard">      
			<a class="wizard-item <%= current_page?(edit_bloc_path) || current_page?(edit_pavement_path) || current_page?(edit_apartment_path) ? 'active' : '' %>" data-rel="1">
        Escolha seu <br>Apartamento
      </a>
			<a class="wizard-item <%= current_page?(edit_document_path) ? 'active' : '' %>"  data-rel="2">
        Envio da <br>Documentação
      </a>
			<a class="wizard-item <%= current_page?(analyze_path) ? 'active' : '' %>"  data-rel="3">
        Status de <br>Análise
      </a>
			<a class="wizard-item <%= current_page?(edit_contract_path) ? 'active' : '' %>"  data-rel="4">
        Contrato
      </a>
      <a class="wizard-item <%= current_page?(analyze_contract_path) || current_page?(analyze_bank_path) ? 'active' : '' %>"  data-rel="5">
        Acompanhamento<br>Análise da Caixa
      </a>      
	</nav>  
</div>

<div class="row row-same-height hidden-md hidden-lg">
  <p class="col-sm-12 col-xs-height <%= current_page?(edit_bloc_path) ? '' : 'hidden' %>">      
    Escolha seu Bloco
    <small><%= t('steps.description', current_step: 1) %></small>
  </p>
  <p class="col-sm-12 col-xs-height <%= current_page?(edit_pavement_path) ? '' : 'hidden' %>">      
    Escolha seu Pavimento
    <small><%= t('steps.description', current_step: 1) %></small>
  </p>
  <p class="col-sm-12 col-xs-height <%= current_page?(edit_apartment_path) ? '' : 'hidden' %>">      
    Escolha seu Apartamento
    <small><%= t('steps.description', current_step: 1) %></small>
  </p>  
  <p class="col-sm-12 col-xs-height <%= current_page?(edit_document_path) ? '' : 'hidden' %>">      
    Envio da Documentação
    <small><%= t('steps.description', current_step: 2) %></small>
  </p>
  <p class="col-sm-12 col-xs-height <%= current_page?(analyze_path) ? '' : 'hidden' %>">      
    Status do Análise
    <small><%= t('steps.description', current_step: 3) %></small>
  </p>
  <p class="col-sm-12 col-xs-height <%= current_page?(edit_contract_path) ? '' : 'hidden' %>">      
    Contrato
    <small><%= t('steps.description', current_step: 4) %></small>
  </p>  
  <p class="col-sm-12 col-xs-height <%= current_page?(analyze_bank_path) || current_page?(analyze_contract_path) ? '' : 'hidden' %>">      
    Acompanhamento Análise da Caixa
    <small><%= t('steps.description', current_step: 5) %></small>
  </p>	
</div>