config/routes.rb
Rails.application.routes.draw do
  root to: 'landing_page#home'

  get 'legal/termos_de_uso', to: 'landing_page#terms_of_service'
  get 'legal/privacidade', to: 'landing_page#privacy'
  get 'proposito', to: 'landing_page#purpose'
  get 'nossos-diferenciais', to: 'landing_page#differential'
  get 'pontos-educacao', to: 'landing_page#education_points'
  get 'nuestros-diferenciales', to: 'landing_page#differential'
  get 'puntos-educacion', to: 'landing_page#education_points'
  get 'futuros-lancamentos', to: 'landing_page#future_releases'
  get 'futuros-lanzamientos', to: 'landing_page#future_releases'
  get 'simulacao', to: 'landing_page#simulation'
  get 'simulacion', to: 'landing_page#simulation'
  post 'simulacao', to: 'landing_page#simulator'  
  get 'tour-360', to: 'landing_page#tour'  
  get 'sustentabilidade', to: 'landing_page#sustainability'

  get 'callback/document_signature', to: 'shop/contracts#callback'

  post 'webhooks/documents', to: 'webhook/documents#callback'

  localized do
    devise_for :users, only: :sessions, controllers: { sessions: :sessions }
    devise_for :users, only: :sessions, path: :admin

    unauthenticated :user do
      resources :document_downloads do         
        collection do 
          get :donwload_video
        end  
      end  
    end  

    authenticate :user do
      resources :document_downloads, only: [:show] do 
        member do 
          get :donwload_contract          
        end 

        collection do 
          get :donwload_video
        end  
      end  

      scope module: 'customer' do
        resource :contract, only: :show
        resource :user, only: [:edit, :update]
        resource :rg_document, only: [:edit, :update]
        resource :residence_document, only: [:edit, :update]
        resource :employment_document, only: [:edit, :update]
      end

      scope module: :shop do
        resource :bloc, only: [:edit, :update] do 
          get :back
        end 
        resource :pavement, only: [:edit, :update]
        resource :apartment, only: [:edit, :update]
        resources :apartments, only: [:queue] do 
          get :queue
        end    
        resource :document, only: [:edit, :update]
        resource :analyze, only: [:show]
        resource :contract, only: [:edit, :update]
        resource :analyze_contract, only: [:show]
        resource :analyze_bank, only: [:show]
      end

      scope :admin, as: 'admin', module: 'admin' do
        resources :contracts, only: :create
        resources :users, only: [:index, :show, :edit, :update, :destroy] do
          post :approved, on: :member
          post :approved_contract, on: :member   
          post :approved_contract_document, on: :member   
          post :signature_bank, on: :member   
          delete :refuse, on: :member  
          delete :refuse_contract, on: :member   
          delete :refuse_contract_document, on: :member   
          delete :refuse_bank, on: :member       
          
          post :reset_account, on: :member  

          resource :document, only: [:edit, :update]          
        end
      end
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord      
  belongs_to :user, optional: true

  mount_uploader :file, DocumentUploader

  validates :file, presence: true  
  
end

app/controllers/admin/documents_controller.rb
module Admin
  class DocumentsController < ApplicationController
    layout 'application'

    def edit
      @user = user.build_nested            
    end

    def update      
      if user.update(user_params)      
        redirect_to(admin_user_path(user))
      else
        render(:edit)
      end
    end

    private

    def user_params
      params.require(:user).permit(        
        cpf_document_attributes: [:id, :file, :file_cache],
        rg_document_front_attributes: [:id, :file, :file_cache],
        rg_document_back_attributes: [:id, :file, :file_cache],
        employment_document_attributes: [:id, :file, :file_cache],
        residence_document_attributes: [:id, :file, :file_cache],
        contract_attributes: [:id, :file, :file_cache],
        contract_signature_attributes: [:id, :file, :file_cache]        
      ).merge(current_step: :analyze, received: Time.now)
    end

    def user
      @user ||= User.find(params[:user_id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  before_action :set_raven_context

  helper_method :is_py?, :is_br?

  HOSTS_MAPPING = {
    'hupi.com.br'     => 'pt-BR',
    'hupi.com.py'     => 'py',
    'www.hupi.com.br' => 'pt-BR',
    'www.hupi.com.py' => 'py'    
  }

  STEP_ENDPOINTS = {
    bloc: { controller: 'shop/blocs', action: :edit },
    pavement: { controller: 'shop/pavements', action: :edit },
    apartment: { controller: 'shop/apartments', action: :edit },
    document: { controller: 'shop/documents', action: :edit },
    cpf_document: { controller: 'shop/documents', action: :edit },
    rg_document_front: { controller: 'shop/documents', action: :edit },
    rg_document_back: { controller: 'shop/documents', action: :edit },
    residence_document: { controller: 'shop/documents', action: :edit },
    employment_document: { controller: 'shop/documents', action: :edit },
    analyze: { controller: 'shop/analyzes', action: :show },
    contract: { controller: 'shop/contracts', action: :edit },
    contractAnalyze: { controller: 'shop/analyze_contracts', action: :show },
    boxAnalyze: { controller: 'shop/analyze_banks', action: :show },
    finished: { controller: 'shop/analyze_banks', action: :show }        
  }.freeze  

  def check_current_step(step:)        
    return if current_user.current_step.to_sym == step
    redirect_to(current_step_url)
  end

  def current_step_url(user = current_user)    
    endpoint = STEP_ENDPOINTS[user.current_step.to_sym]    
    url_for(endpoint)
  end

  def after_sign_in_path_for(resource)    
    resource.admin? ? admin_users_path : current_step_url(resource)
  end

  def is_py?
    I18n.locale == :'py'
  end

  def is_br?
    I18n.locale == :'pt-BR'
  end

  private

  def set_raven_context
    Raven.user_context(id: session[:current_user_id])
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end

  def set_locale        
    if Rails.env.development?
      I18n.locale = :'pt-BR'
    else  
      I18n.locale = HOSTS_MAPPING[request.host] || I18n.default_locale      
    end      
  end
end

app/controllers/shop/documents_controller.rb
module Shop
  class DocumentsController < ApplicationController
    layout 'application'

    def edit
      @user = current_user.build_nested            
    end

    def update      
      if current_user.update(user_params)      
        redirect_to(analyze_pt_br_path)
      else
        render(:edit)
      end
    end

    private

    def user_params
      if User.current_steps[current_user.current_step].to_i >= User.current_steps[:analyze]
        if current_user.received.nil?
          params.require(:user).permit(
            :disapproved,
            cpf_document_attributes: [:id, :file, :file_cache],
            rg_document_front_attributes: [:id, :file, :file_cache],
            rg_document_back_attributes: [:id, :file, :file_cache],
            employment_document_attributes: [:id, :file, :file_cache],
            residence_document_attributes: [:id, :file, :file_cache]
          ).merge(received: Time.now)
        else  
          params.require(:user).permit(
            :disapproved,
            cpf_document_attributes: [:id, :file, :file_cache],
            rg_document_front_attributes: [:id, :file, :file_cache],
            rg_document_back_attributes: [:id, :file, :file_cache],
            employment_document_attributes: [:id, :file, :file_cache],
            residence_document_attributes: [:id, :file, :file_cache]
          )
        end  
      else  
        params.require(:user).permit(
          :disapproved,
          cpf_document_attributes: [:id, :file, :file_cache],
          rg_document_front_attributes: [:id, :file, :file_cache],
          rg_document_back_attributes: [:id, :file, :file_cache],
          employment_document_attributes: [:id, :file, :file_cache],
          residence_document_attributes: [:id, :file, :file_cache]
        ).merge(current_step: :analyze, received: Time.now)
      end        
    end
  end
end

app/controllers/webhook/documents_controller.rb
class Webhook::DocumentsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :validate

  def callback   
    render :nothing => true, :status => 200
  end  

  private

  def validate
    ClickSign.validate_callback params[:event][:name], params[:document][:key], request
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(separator = " - ")    
    return content_for?(:title) ? content_for(:title).concat("#{separator}#{app_name}") : app_name;
  end

  def app_name
    'HUPI'
  end
end

app/views/application/documents/_edit.html.erb
<div class="page-header">
  <div class="container text-center">    
    <% unless current_user.admin? %>
      <%= render 'layouts/shared/wizard' %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row row-same-height">
    <h1 class="col-sm-12 col-xs-height"><%= t('.title') %></h1>
  </div>
  <%= form_for @user, url: current_user.admin? ? admin_user_document_path(@user) : document_path, method: :patch, html: { multipart: true } do |f| %>
    <%= f.hidden_field :disapproved, value: nil %>  
    <div class="panel panel-default p15">
      <div class="panel-body">
        <% if flash[:alert] %>
          <div class="alert alert-danger"><%= flash[:alert] %></div>
        <% end %>        

        <%= render(partial: 'instructions', locals: { text: t('.instructions') }) %>
  
        <div class="row">
          <div class="col-md-6 text-center">
            <h3><%= t('.cpf') %></h3>
            <h6><%= t('.cpf_title') %></h6>
            <div id="cpf_document">               
              <%= f.fields_for :cpf_document do |cpf| %>
                <div class="preview cpf-upload-preview">                                                                          
                  <% unless cpf.object.file.blank? %>
                    <%= image_tag(cpf.object.file, class: "img-uploaded img-responsive") %>
                  <% else %>  
                    <%= image_tag("", class: "img-uploaded img-responsive") %>
                  <% end %>  
                </div>    
                <% if cpf.object.file.blank? %>            
                  <fieldset>
                    <label for="user_cpf_document_attributes_file" class="custom-file-upload">
                      <i class="fa fa-cloud-upload"></i> Carregar imagem
                    </label>
                    <%= cpf.file_field :file, 'data-document' => "cpf", required: true,class: 'form-control file', accept: '.pdf,image/*' %>
                    <%= cpf.hidden_field :file_cache %>                                    
                  </fieldset>     
                <% end %>                                              
              <% end %>
            </div>            
          </div>

          <div class="col-md-6 text-center">
            <h3><%= t('.rg') %></h3>
            <h6><%= t('.rg_title') %></h6>
            <div id="rg_documents">     
              <div class="row">               
                <%= f.fields_for :rg_document_front do |rg| %>
                  <%= render 'application/documents/commons/rg_fields', f: rg, type: 0 %>
                <% end %>                     

                <%= f.fields_for :rg_document_back do |rg| %>
                  <%= render 'application/documents/commons/rg_fields', f: rg, type: 1 %>
                <% end %>                                               
              </div>  
            </div>            
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 text-center">
            <h3><%= t('.employment') %></h3>
            <h6><%= t('.employment_title') %></h6>
            <div id="employment_document">               
              <%= f.fields_for :employment_document do |employment| %>
                <div class="preview employment-upload-preview">                                                                                        
                  <% unless employment.object.file.blank? %>
                    <%= image_tag(employment.object.file, class: "img-uploaded img-responsive") %>
                  <% else %>  
                    <%= image_tag("", class: "img-uploaded img-responsive") %>
                  <% end %>  
                </div>
                <% if employment.object.file.blank? %>
                  <fieldset>
                    <label for="user_employment_document_attributes_file" class="custom-file-upload">
                      <i class="fa fa-cloud-upload"></i> Carregar imagem
                    </label>
                    <%= employment.file_field :file, required: true, 'data-document' => "employment", class: 'form-control file', accept: '.pdf,image/*' %>
                    <%= employment.hidden_field :file_cache %>
                  </fieldset>                  
                <% end%>  
              <% end %>
            </div>            
          </div>
          <div class="col-md-6 text-center">
            <h3><%= t('.residence') %></h3>
            <h6><%= t('.residence_title') %></h6>
            <div id="residence_document">               
              <%= f.fields_for :residence_document do |residence| %>
                <div class="preview residence-upload-preview">                                                                          
                  <% unless residence.object.file.blank? %>
                    <%= image_tag(residence.object.file, class: "img-uploaded img-responsive") %>
                  <% else %>  
                    <%= image_tag("", class: "img-uploaded img-responsive") %>
                  <% end %>  
                </div>
                <% if residence.object.file.blank? %>
                  <fieldset>
                    <label for="user_residence_document_attributes_file" class="custom-file-upload">
                      <i class="fa fa-cloud-upload"></i> Carregar imagem
                    </label>
                    <%= residence.file_field :file, required: true, 'data-document' => "residence", class: 'form-control file', accept: '.pdf,image/*' %>
                    <%= residence.hidden_field :file_cache %>
                  </fieldset>      
                <% end %>                
              <% end %>
            </div>            
          </div>
        </div>
      </div>
    </div>

    <div class="button-group">
      <% if current_user.admin? %>
        <%= link_to t('.cancel'), admin_user_path(@user), class: 'btn btn-lg btn-default' %>
        <%= f.submit t('.save'), class: 'btn btn-lg btn-success' %>
      <% else %>  
        <%= link_to t('.back'), edit_apartment_path, class: 'btn pull-left btn-lg btn-default' %>
        <%= f.submit t('.next'), class: 'btn btn-lg btn-success' %>
      <% end %>            
    </div>
  <% end %>
</div>